name: guia_go
description: "Guia Go"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  shimmer: ^3.0.0
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  provider: ^6.1.2
  carousel_slider: ^5.0.0
  collection: ^1.19.0
  dots_indicator: ^3.0.0
  expandable_page_view: ^1.0.17
  mockito: ^5.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
  strict: ^2.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/