// Mocks generated by Mockito 5.4.5 from annotations
// in guia_go/test/modules/go_now/domain/use_cases/get_motels_go_now_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:guia_go/core/resources/resource.dart' as _i2;
import 'package:guia_go/modules/go_now/data/models/motel_list_data_model.dart'
    as _i5;
import 'package:guia_go/modules/go_now/domain/repositories/imotel_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResource_0<T, E> extends _i1.SmartFake
    implements _i2.Resource<T, E> {
  _FakeResource_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IMotelRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIMotelRepository extends _i1.Mock implements _i3.IMotelRepository {
  MockIMotelRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Resource<_i5.MotelListDataModel, Exception>> getMotelList() =>
      (super.noSuchMethod(
            Invocation.method(#getMotelList, []),
            returnValue: _i4.Future<
              _i2.Resource<_i5.MotelListDataModel, Exception>
            >.value(
              _FakeResource_0<_i5.MotelListDataModel, Exception>(
                this,
                Invocation.method(#getMotelList, []),
              ),
            ),
          )
          as _i4.Future<_i2.Resource<_i5.MotelListDataModel, Exception>>);
}
